version: "3.9"
services:
  user-service:
    build: 
      context: .
      dockerfile: ./services/user-service/Dockerfile
    env_file:
      - ./.env 
    ports:
      - "8001:8000"
  ingestion-service:
    build: ./services/ingestion-service
    ports:
      - "8002:8000"
  alerting-service:
    build: ./services/alerting-service
    ports:
      - "8003:8000"
  notification-service:
    build: ./services/notification-service
    ports:
      - "8004:8000"
  ml-service:
    build: ./services/ml-prediction-service
    ports:
      - "8005:8000"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
volumes:
  pg_data:
